### PR TITLE
Adding node_exporter_binary_local_dir to set a local Binary to use

### PR DESCRIPTION
**Pull request by manuel-held**

### CODE REVIEW

**Comment by manuel-held** [comment]
Pull Request for #2

**Review by jinja2ninja — APPROVED** [review]
I made a few changes to the conditional, but this looks great. Good idea and thanks for contributing!

**Review by jinja2ninja — APPROVED** [review]

**Comment by jinja2ninja** [comment]
I seem to be getting an issue with the integration test (which should entirely unrelated to this PR). I will merge this once I get that all sorted

**Comment by jinja2ninja** [comment]
I ended up having to change the test for the grafana server to get it to pass, but it should be good to go. Thanks again!

**Pull request merged**
